import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed); 
		
		int kids=0;
		int total=0 ;
		int twoKids=0;
		int threeKids=0;
		int fourOrMore=0;
		int count=0;
		

		for (int i=0; i<T; i++) {
		boolean girl= true;
		boolean boy= true;
		
		int numOfKids=0;
		 while (girl || boy) {
			 kids = 0 ;
			 double rnd = generator.nextDouble();
			  if (rnd == 1) {
			  girl= false;
			  kids++;
			  }
			  else { 
				  
				  boy= false;
                  kids++;					  
			  }
			  total ++;
			numOfKids++;
		 }
		switch(numOfKids) {
			case 2:
				twoKids++;
				break;
			case 3:
				threeKids++;
				break;
			default:
				fourOrMore++;
				break;
			}
		}
		 int check= Math.max(Math.max(twoKids, threeKids), fourOrMore);
		 double avarage = (double) total / T;
	     System.out.println("Avrage: " +avarage+ "children to get at least one of each gender.");
		 System.out.println("Number of families with 2 children: "+ twoKids);
		 System.out.println("Number of families with 3 children: " + threeKids);
		 System.out.println("Number of families with 4 children: "+ fourOrMore);
		 System.out.println("The most common number is " + check + ".");
		 
		
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
